Manual/Manual.pdf       usr/share/doc/frown-doc/
Manual/html             usr/share/doc/frown-doc/
QuickStart		usr/share/doc/frown-doc/examples
Manual/Examples/*.lg	usr/share/doc/frown-doc/examples/manual
Manual/Examples/*.lhs	usr/share/doc/frown-doc/examples/manual
Examples/*.g		usr/share/doc/frown-doc/examples/other
Examples/*.lg		usr/share/doc/frown-doc/examples/other
Examples/Haskell	usr/share/doc/frown-doc/examples/other
