=head1 NAME

haddock-collect - add location line to hoogle txt database

=head1 SYNOPSIS

B<haddock-collect> S<I<string_strip_path>> S<I<output_dir>>

=head1 DESCRIPTION

haddock-collect is a program that helps to add location line to hoogle txt database.

This script takes STDIN to find hoogle txt database filenames, and put each files with location line on output_dir.
This script is called from hlibrary.mk, if haskell packages are built.

=head1 SEE ALSO

L<hoogle(1)>
L<haddock(1)>

=head1 AUTHOR

Kiwamu Okabe <kiwamu@debian.or.jp>
