./prims/common/*.primitives.yaml usr/share/clash-lib/prims/common
./prims/commonverilog/*.primitives.yaml usr/share/clash-lib/prims/commonverilog
./prims/systemverilog/*.primitives.yaml usr/share/clash-lib/prims/systemverilog
./prims/verilog/*.primitives.yaml usr/share/clash-lib/prims/verilog
./prims/vhdl/*.primitives.yaml usr/share/clash-lib/prims/vhdl
dist-ghc/build/v16-upgrade-primitives/v16-upgrade-primitives usr/bin
