.TH UNLAMBDA 1 "October 07 2013"
.SH NAME
unlambda \- an unlambda programming language interpreter
.SH SYNOPSIS
.B \fBunlambda\fP
.SH DESCRIPTION
\fBunlambda\fP reads an unlambda program from the standard input, and prints the
processed information to the standard output.

.SH OPTIONS
None.
.SH AUTHOR
.nh
\fBunlambda\fP was written by Ørjan Johansen and Don Stewart

This manual page was written by Raúl Benencia for the Debian Project.
