.TH GNOME-FLASHBACK-XMONAD 1 "September 6, 2015"
.SH NAME
gnome-flashback-xmonad \- Start a GNOME Flashback session with XMonad
as the window manager
.SH SYNOPSIS
.B gnome-flashback-xmonad
.I arguments
.SH DESCRIPTION
.B gnome-flashback-xmonad
is a simple shell script that starts a GNOME Flashback session (i.e.,
a session without GNOME Shell) with XMonad as the window manager.

Any command line arguments supplied will be passed on to
\fBgnome-session\fR(1).

.SH AUTHOR
Per Olofsson <pelle@debian.org>
