.de EX
.ne 5
.if n .sp 1
.if t .sp .5
.nf
.in +.5i
..
.de EE
.fi
.in -.5i
.if n .sp 1
.if t .sp .5
..
.TH XMONAD-SESSION 1 "November 24, 2011"
.SH NAME
xmonad-sesssion \- Starts the XMonad window manager as a session
.SH SYNOPSIS
.B xmonad-session
.RI arguments
.SH DESCRIPTION
xmonad-session is a simple shell script that starts sources the content of
~/.xmonad/xmonad-session-rc (if that file exists) and then starts XMonad.

Any command line arguments supplied will be passed on to XMonad.

.SH AUTHOR
This manpage was written by Erik de Castro Lopo <erikd@mega-nerd.com> and modified
by Joachim Breitner <nomeata@debian.org> for the Debian GNU/Linux system (but
may be used by others).
