.TH HSBRAINFUCK 1 "October 07 2013"
.SH NAME
hsbrainfuck \- a brainfuck programming language interpreter
.SH SYNOPSIS
.B \fBhsbrainfuck\fP
.SH DESCRIPTION
\fBhsbrainfuck\fP reads a brainfuck program from the standard input, and prints the
processed information to the standard output.

The original name of the program is \fBbf\fP, but it was changed to
\fBhsbrainfuck\fP in order to suit some needs of the Debian project.

.SH OPTIONS
None.
.SH AUTHOR
.nh
\fBhsbrainfuck\fP was written by Jason Dagit <dagit@codersbase.com>.

This manual page was written by Raúl Benencia for the Debian project.
