.TH HELIUM "1" "December 2006" "Helium compiler 1.6 (Fri Feb  3 14:53:36 RST 2006)" "User Commands"
.SH NAME
helium \- compiler used for learning the programming language Haskell
.SH SYNOPSIS
.B helium
[\fIoptions\fP] \fIfile\fP
.SH DESCRIPTION
The Helium compiler reads Haskell source files and compiles them into instruction files for the Lazy Virtual Machine.
These instruction files can then be run by the Lazy Virtual Machine interpreter \fBlvmrun\fP.
.SH OPTIONS
.TP
\fB\-b\fP, \fB\-\-build\fP
recompile module even if up to date
.TP
\fB\-B\fP, \fB\-\-build\-all\fP
recompile all modules even if up to date
.TP
\fB\-i\fP, \fB\-\-dump\-information\fP
show information about this module
.TP
\fB\-I\fP, \fB\-\-dump\-all\-information\fP
show information about all imported modules
.TP
\fB\-l\fP, \fB\-\-no\-logging\fP
do not send log information
.TP
\fB\-o\fP, \fB\-\-overloading\fP
turn overloading on
.TP
\fB\-P\fP PATH, \fB\-\-lvmpath\fP=\fIPATH\fP
use PATH as search path
.TP
\fB\-v\fP, \fB\-\-verbose\fP
show the phase the compiler is in
.TP
\fB\-w\fP, \fB\-\-no\-warnings\fP
do not show warnings
.TP
\fB\-X\fP, \fB\-\-more\-options\fP
show more compiler options
.TP
\fB\-\-info\fP=\fINAME\fP
display information about NAME
.SH COPYRIGHT
.PP
\(co 1999,2001 Daan Leijen <daan@cs.uu.nl>
.PP
\(co           Bastiaan Heerden <bastiaan@cs.uu.nl>
.PP
This package is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation.
This package is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this package; if not, write to the Free Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
.SH "SEE ALSO"
.BR lvmrun (1)
.PP
.SH AUTHOR
This manual page was written by Arjan Oosting <arjanoosting@home> for the Debian system and is also licensed under the terms of the GNU General Public License version 2.
