.TH hdevtools 1
.SH NAME
hdevtools \- GHC powered daemon for fast Haskell development
.SH SYNOPSIS
.B hdevtools [COMMAND] ... [OPTIONS]
.SH DESCRIPTION
.BR hdevtools
is typically run from an editor plugin, such as
Syntastic or vim-hdevtools.
.P
It can also be used manually at the command
line to check individual files for problems ("hdevtools check file"),
or to control the daemon ("hdevtools --stop-server"). For details, see
"hdevtools --help", or the README.
