.TH SHELLCHECK 1 "23 JUNE 2014"
.SH NAME
shellcheck \- analyse shell scripts
.SH SYNOPSIS
\fBshellcheck\fP [ \-f \fIformat\fP ] [ \-e \fIcode\fP ] [ \-s \fIshell\fP ] \fIfiles\fP
.SH DESCRIPTION
\fBshellcheck\fP syntactically analyzes shell scripts and points out typical issues.
Among other things, it is able to spot wrong usage of unicode characters, non-matching parentheses, wrong spacing, usage of features unavailable to the selected shell, corner cases with respect to quoting, needlessly complex snippets and unused variables.
The analysis does not actually execute any shell commands.
.SH OPTIONS
.TP
\fB\-f\fP \fIformat\fP, \fB\-\-format\fP \fIformat\fP
Select the format used for printing diagnostics.
Available formats are \fBcheckstyle\fP (XML based format), \fBgcc\fP, \fBjson\fP and and \fBtty\fP (colorful).
The default format is \fBtty\fP.
.TP
\fB\-e\fP \fIcode\fP, \fB\-\-exclude\fP \fIcode\fP
Suppress emission of given diagnostic codes.
Diagnostic codes consist of four decimal digits.
To suppress multiple codes, the option can be given multiple times or codes can be separated using commas.
.TP
\fB\-s\fP \fIshell\fP, \fB\-\-shell\fP \fIshell\fP
Select shell dialect.
Available shells are \fBbash\fP, \fBksh\fP (Korn shell), \fBsh\fP (POSIX compatible), and \fBzsh\fP.
If this option is not given, the dialect is guessed from the shebang.
Defaults to \fBbash\fP.
.SH "SEE ALSO"
.BR bash (1),
.BR ksh (1),
.BR sh (1),
.BR zsh (1)
.SH AUTHORS
shellcheck was written by Vidar Holen.
.PP
This manual page was written by Helmut Grohne for the Debian project (but may be used by others).
