.TH UPDATE-HOOGLE 8 "September 2012" "Debian GNU/Linux"
.SH "NAME"
.LP
update-hoogle \- Update hoogle database
.SH "SYNOPSIS"
.LP
update-hoogle
.SH "DESCRIPTION"
.LP
This program creates hoogle database for Debian system.
It collects haddock documents, then create the database for hoogle command.
.PP
.B update\-hoogle
isn't called automatically when
.B libghc\-*\-doc
package installed.
You should run this program manually to synchronize hoogle database with
haddock documents.
.SH "FILES"
.TP
.B /var/lib/hoogle/databases
Here is hoogle database files.
They are updated by update-hoogle command.
.SH "AUTHOR"
.LP
Kiwamu Okabe <kiwamu@debian.or.jp>
.SH "SEE ALSO"
.LP
hoogle(1), haddock(1)
